### ISSUE TITLE
getSecondMoveofGame()

### ISSUE THREAD

**Issue by gordonkoehn** [nyxxsudios/JinxTogether#2]
We need a Methode that calculates the second move. It should be quite the same as with the getFirstMove(). We just need the biggest corridor in Y-axis somewhere in the middle.

**Comment by gordonkoehn** [comment]
I just finished it. It works the following way:
It will place its move in the same rowX as the opponent. In the Y Dimension, it will always at least be 4 fields away. Furthermore, the function will try to place the move in the middle of the biggest possible Y Corridor. 

I know its poorly coded!

**Comment by 7jep7** [comment]
Great, I will have a look tomorrow
